## Nornir Groups File 
---
IOS:
  username: cisco
  password: cisco
  platform: ios
  port: 22
  connection_options:
    napalm:
      platform: ios
      extras:
        optional_args:
          key_file: ~/.ssh/id_rsa
          use_keys: True